springdoc:
  swagger-ui:
    path: /swagger
spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  batch:
    jdbc:
      initialize-schema: always
  data:
    web:
      pageable:
        one-indexed-parameters: true
  messages:
    encoding: UTF-8
    basename: messages.messages