springdoc:
  swagger-ui:
    path: /swagger

spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  data:
    web:
      pageable:
        one-indexed-parameters: true