spring:
  jwt:
    secret-key: 05f5c4e6f276317512bc90c48e681554cd80f2cdee32c9f9e5db4dde1c02948649c57b4f9b96d42331157bae963ad02564bda23b492cccb039e0abe529b58ef3
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4bf4d33707b011b4b3299e123000c050
            client-secret: I6UtzO2uftwKQodI9gmB0Fo3YOAfIsHO
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          google:
            client-id: 59991953401-uj0o6c4lpvj2ppc4sn81e3no1dqq30qp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id